### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dpotter895** [dpotter895/TheFinalBudget#1]
- [ ] Use embedded database instead of sql server
- [ ] Clean up code
- [ ] First time (in app) guide
- [ ] Complete comprehensive ReadMe
- [ ] Add a manual transaction
- [ ] Hide a category
